# Generated by Django 3.2.13 on 2022-05-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.BooleanField()),
                ('pclass', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=6)),
                ('age', models.FloatField(null=True)),
                ('sibsp', models.IntegerField(null=True)),
                ('parch', models.IntegerField(null=True)),
                ('ticket', models.CharField(max_length=20, null=True)),
                ('fare', models.FloatField(null=True)),
            ],
        ),
    ]
